# This is the network config written by 'subiquity'
network:
  ethernets:
    ens160:
      addresses: [172.16.1.4/24]
      routes:
        - to: 0.0.0.0/0
          via: 172.16.1.2
      nameservers:
        search: [sys265.local]
        addresses: [172.16.1.12, 172.16.1.13]
      dhcp4: no
  version: 2
